### ISSUE TITLE
[Feature] Send file over LAN

### ISSUE THREAD

**Issue by AntoninLoubiere** [CopyPastaOfficial/CopyPasta#7]
The feature that I want is the ability to send files across computer / phones like the application over the LAN  [Dukto R6](https://github.com/guilhem/dukto) that allows you to send file over the LAN, but it is no longer maintained. It is more convenient than using an USB stick. And will respect the theme of the app.

**Comment by ThaaoBlues** [comment]
I think that's a really great idea. We should add this feature on a future update when the play store will have accepted our app ^^

**Comment by AntoninLoubiere** [comment]
I has been implemented, this issue should be closed.
